# Generated by Django 5.2 on 2025-04-19 23:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "player2_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, null=True),
                ),
                ("current_player_id", models.UUIDField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting for players"),
                            ("IN_PROGRESS", "In progress"),
                            ("FINISHED", "Finished"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("winner_id", models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.UUIDField()),
                (
                    "x",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                (
                    "y",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("H", "Horizontal"), ("V", "Vertical")], max_length=1
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quoridor.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.UUIDField()),
                (
                    "pawn_position_x",
                    models.IntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "pawn_position_y",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(8),
                        ]
                    ),
                ),
                ("remaining_fences", models.IntegerField(default=10)),
                (
                    "goal_side",
                    models.CharField(
                        choices=[("TOP", "Top"), ("BOTTOM", "Bottom")], max_length=10
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quoridor.game"
                    ),
                ),
            ],
        ),
    ]
