# Generated by Django 5.2 on 2025-04-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoridor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fence",
            name="player_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="game",
            name="current_player_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="player1_id",
            field=models.CharField(default="player1", editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="game",
            name="player2_id",
            field=models.CharField(default="player2", editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="game",
            name="winner_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="playerstate",
            name="player_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="playerstate",
            unique_together={("game", "player_id")},
        ),
    ]
